// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpiYOYzu7NGZKQHP1qLlRkkM9CcXvZ-eE',
    appId: '1:972145849986:android:28a4e28a947632a6aea69b',
    messagingSenderId: '972145849986',
    projectId: 'feelback-536d4',
    storageBucket: 'feelback-536d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYwnOs-NPl7Ps59dgsrBjbcfTaAwkkFYk',
    appId: '1:972145849986:ios:6498d76addac9d78aea69b',
    messagingSenderId: '972145849986',
    projectId: 'feelback-536d4',
    storageBucket: 'feelback-536d4.firebasestorage.app',
    iosBundleId: 'com.example.feelback',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBl5u5aP8dBsz3vRsdAQKNYmsVadr15Kk',
    appId: '1:972145849986:web:4e947987fb156892aea69b',
    messagingSenderId: '972145849986',
    projectId: 'feelback-536d4',
    authDomain: 'feelback-536d4.firebaseapp.com',
    storageBucket: 'feelback-536d4.firebasestorage.app',
    measurementId: 'G-B9G27E9DZ1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYwnOs-NPl7Ps59dgsrBjbcfTaAwkkFYk',
    appId: '1:972145849986:ios:6498d76addac9d78aea69b',
    messagingSenderId: '972145849986',
    projectId: 'feelback-536d4',
    storageBucket: 'feelback-536d4.firebasestorage.app',
    iosBundleId: 'com.example.feelback',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBl5u5aP8dBsz3vRsdAQKNYmsVadr15Kk',
    appId: '1:972145849986:web:3ef2f60e301bd7ffaea69b',
    messagingSenderId: '972145849986',
    projectId: 'feelback-536d4',
    authDomain: 'feelback-536d4.firebaseapp.com',
    storageBucket: 'feelback-536d4.firebasestorage.app',
    measurementId: 'G-GKDKFXD4GS',
  );

}